### ISSUE TITLE
Constant LUA Error, pops up every 30 seconds..

### ISSUE THREAD

**Issue by MisterNegative** [Jaliborc/Bagnon#1751]
### have lastest version installed through curseforge and I get this LUA Error every 30 seconds non stop.

![image](https://github.com/Jaliborc/Bagnon/assets/29007320/ba4039c4-fed2-4ea0-a5d6-606f876a3cb4)

Message: Interface/AddOns/BagBrother/core/api/owners.lua:75: invalid order function for sorting
Time: Sat Sep  2 11:43:15 2023
Count: 1
Stack: Interface/AddOns/BagBrother/core/api/owners.lua:75: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/BagBrother/core/api/owners.lua"]:75: in function `Sort'
[string "@Interface/AddOns/BagBrother/core/api/owners.lua"]:66: in function `?'
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
}
(*temporary) = <function> defined @Interface/AddOns/BagBrother/core/api/owners.lua:75
(*temporary) = <table> {
 profile = <table> {
 }
 isguild = 16
 name = "Death and Glory"
 address = "®Death and Glory-Silvermoon"
 id = "Death and Glory*"
 offline = true
 cache = <table> {
 }
 realm = "Silvermoon"
}
(*temporary) = <table> {
 profile = <table> {
 }
 isguild = 16
 name = "Death and Glory"
 address = "®Death and Glory-Silvermoon"
 id = "Death and Glory*"
 offline = true
 cache = <table> {
 }
 realm = "Silvermoon"
}
(*temporary) = <table> {
 profile = <table> {
 }
 isguild = 9
 name = "Entropia"
 address = "®Entropia-Silvermoon"
 id = "Entropia*"
 offline = true
 cache = <table> {
 }
 realm = "Silvermoon"
}

**Comment by jeske** [comment]
There seems to be something about the isguild conditional that lua doesn't like. im not familiar enough with lua sort or this addon to know why. Just randomly guessing, maybe the sort function expects to see only nil or 1 as return values, and b.isguild doesn't have to be nil or 1, but I'm not sure.

You can remove the isguild conditional entirely and the error goes away.

I replaced the sort function with this and it also seems to go away. This is testing that neither isguild is nil, to be sure we are comparing two numbers against eachother, then using the < operator to compare them.

```
        sort(self.ordered, function(a, b)
		if (a.isguild and b.isguild) and a.isguild ~= b.isguild then
			return a.isguild < b.isguild
		elseif a.level == b.level or not (a.level and b.level) then
			return a.name < b.name
		end
		return a.level > b.level
	end)
```

**Comment by Jaliborc** [comment]
> There seems to be something about the isguild conditional that lua doesn't like. im not familiar enough with lua sort or this addon to know why. Just randomly guessing, maybe the sort function expects to see only nil or 1 as return values, and b.isguild doesn't have to be nil or 1, but I'm not sure.
> 
> You can remove the isguild conditional entirely and the error goes away.
> 
> I replaced the sort function with this and it also seems to go away. This is testing that neither isguild is nil, and then that they are not equal, to be sure we are comparing two numbers against eachother, then using the < operator to compare them.
> 
> ```
>         sort(self.ordered, function(a, b)
> 		if (a.isguild and b.isguild) and a.isguild ~= b.isguild then
> 			return a.isguild < b.isguild
> 		elseif a.level == b.level or not (a.level and b.level) then
> 			return a.name < b.name
> 		end
> 		return a.level > b.level
> 	end)
> ```
> 
> I don't have time to do a pull request right now, but i'll try to get around to it if nobody else picks this up and patches.

That's already a big help in figuring out the cause, narrowing it down to the guild part. I'll fix this quickly now.

**Comment by Jaliborc** [comment]
Ah. isguild is suppose to be a boolean, but because I'm an idiot it's an integer. Fixed in upcoming version I believe.

**Comment by MisterNegative** [comment]
Error still the same after updating to latest version...


Message: Interface/AddOns/BagBrother/core/api/owners.lua:75: invalid order function for sorting
Time: Sat Sep  9 13:53:58 2023
Count: 11
Stack: Interface/AddOns/BagBrother/core/api/owners.lua:75: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/BagBrother/core/api/owners.lua"]:75: in function `Sort'
[string "@Interface/AddOns/BagBrother/core/api/owners.lua"]:66: in function `?'
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
}
(*temporary) = <function> defined @Interface/AddOns/BagBrother/core/api/owners.lua:75
(*temporary) = <table> {
 isguild = 16
 cache = <table> {
 }
 id = "Death and Glory*"
 profile = <table> {
 }
 name = "Death and Glory"
 address = "®Death and Glory-Silvermoon"
 offline = true
 counts = <table> {
 }
 realm = "Silvermoon"
}
(*temporary) = <table> {
 isguild = 16
 cache = <table> {
 }
 id = "Death and Glory*"
 profile = <table> {
 }
 name = "Death and Glory"
 address = "®Death and Glory-Silvermoon"
 offline = true
 counts = <table> {
 }
 realm = "Silvermoon"
}
(*temporary) = <table> {
 isguild = 13
 cache = <table> {
 }
 id = "Pub Crawlers*"
 profile = <table> {
 }
 name = "Pub Crawlers"
 address = "®Pub Crawlers-Silvermoon"
 offline = true
 counts = <table> {
 }
 realm = "Silvermoon"
}
